/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatPlayground: typeof import('./components/chat/ChatPlayground.vue')['default']
    Dialog: typeof import('./components/common/Dialog.vue')['default']
    JsonNode: typeof import('./components/common/JsonNode.vue')['default']
    JsonTreeViewer: typeof import('./components/common/JsonTreeViewer.vue')['default']
    Layout: typeof import('./components/layout/Layout.vue')['default']
    LoadingModal: typeof import('./components/common/LoadingModal.vue')['default']
    MultiModalRuleDialog: typeof import('./components/channel/MultiModalRuleDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchableSelect: typeof import('./components/common/SearchableSelect.vue')['default']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
    SvgIcon: typeof import('./components/common/SvgIcon.vue')['default']
    TodayTrendChart: typeof import('./components/dashboard/TodayTrendChart.vue')['default']
  }
}
