/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Layout: typeof import('./components/layout/Layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchableSelect: typeof import('./components/common/SearchableSelect.vue')['default']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
    SvgIcon: typeof import('./components/common/SvgIcon.vue')['default']
  }
}
